# Generated by Django 3.1.4 on 2021-02-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='code',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
    ]
